# Generated by Django 4.2.7 on 2023-12-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creature_name", models.TextField()),
                ("initiative_value", models.IntegerField(default=0)),
                ("hit_points", models.IntegerField(default=1)),
                (
                    "encounter",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="initiative.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiative_value"],
            },
        ),
    ]
