# Generated by Django 4.2.7 on 2023-12-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("initiative", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="encounter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="initiative.encounter",
            ),
        ),
    ]
